### ISSUE TITLE
ARL not saved after container restart

### ISSUE THREAD

**Issue by olimeca** [codefaux/deemix-for-lidarr#5]
Using the following in my compose:

      - ${APPDATA}/deemix/config:/deemix-gui/config

Each time the container is restarted I have to populate the ARL token again. Is this expected?

**Comment by codefaux** [comment]
Apologies for the delay, Github isn't notifying me of new issues, I'll look into that...

> Each time the container is restarted I have to populate the ARL token again. Is this expected?

No. It retains all information on my system including ARL, but I'm not using environment-variable-redirected folders, and I'm on Linux. Haven't tested on Windows, specifically.

Immediately after restart, it does take ten or so seconds for Deemix to log back in and show the account/ARL in the settings box. I imagine you've given it enough time, though. Do you have any logs which might be helpful?

I don't know where ${APPDATA} is on your system or what permissions Docker has on your system within that folder domain, but perhaps try using a folder with generally open permissions and see if this helps?

Is the ARL the *only* item lost on container restart? If *all* configuration is lost on container restart/recreation, suspect your mountpoint (most likely its permissions) but if the ARL is the *only* item being lost, it's likely related to the ARL, or Deemix itself. I can help with troubleshooting, but I'm not a developer on either the Lidarr, deemix-for-lidarr plugin, or Deemix projects; my work here is purely in tieing other people's projects together.

**Comment by olimeca** [comment]
I ended up blowing away the container and settings and starting again. The ARL is being saved after restarts now. Not sure what happened but everything appears to be working now. Thanks!
