### ISSUE TITLE
Config mount mapping

### ISSUE THREAD

**Issue by 909oce** [codefaux/deemix-for-lidarr#7]
Dockerfile shows volume created /config but compose file example shows /deemix-gui/config. I've used the compose mapping and all works fine, however this causes the container to create an unnamed volume each time its started linking to /config. Unsure if this was a typo in the Dockerfile or compose file.

Not a huge deal, just wanted to point it out and clarify which mount I should be using for config.

**Comment by codefaux** [comment]
Good catch, it's the type of thing I'd also be annoyed by if I noticed it. Should be fixed, reopen if necessary.
